import{a as y,S as m,i as h}from"./assets/vendor-DEenWwFD.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const g="47413838-05ed4088691502c79710d9d69",b="https://pixabay.com/api/",i=document.querySelector(".gallery"),L=document.querySelector(".search-form"),p=document.querySelector(".loader-container"),d=document.querySelector(".load-more-btn");let a=1,u="";L.addEventListener("submit",async function(o){o.preventDefault(),u=document.querySelector(".search-query").value,a=1,await f(u)});d.addEventListener("click",function(){a++,f(u,a)});async function f(o,n=1){p.style.display="flex";try{const s=(await y.get(b,{params:{key:g,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:n,per_page:15}})).data;if(a===1&&(i.innerHTML=""),o.trim()===""){l("Sorry, there are no images matching your search query. Please try again!");return}v(s.hits),n*15>=s.totalHits?(d.style.display="none",l("We're sorry, but you've reached the end of search results.")):d.style.display="block";const t=i.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy({top:t*2,left:0,behavior:"smooth"})}catch(r){l("An error occurred. Please try again."),console.error("Axios error:",r)}finally{p.style.display="none"}}function v(o){a===1&&(i.innerHTML=""),o.forEach(function(r){const s=document.createElement("div");s.classList.add("image-card"),s.innerHTML=`
            <a href="${r.largeImageURL}" data-lightbox="gallery">
                <img src="${r.webformatURL}" alt="${r.tags}">
            </a>
            <div class="image-info">
                <p>Likes: ${r.likes}</p>
                <p>Views: ${r.views}</p>
                <p>Comments: ${r.comments}</p>
                <p>Downloads: ${r.downloads}</p>
            </div>
        `,i.appendChild(s)}),new m(".image-card a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}function l(o){h.error({title:"Error",message:o})}
//# sourceMappingURL=index.js.map
