import{a as y,S as m,i as h}from"./assets/vendor-DEenWwFD.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const g="47413838-05ed4088691502c79710d9d69",L="https://pixabay.com/api/",i=document.querySelector(".gallery"),b=document.querySelector(".search-form"),p=document.querySelector(".loader-container"),d=document.querySelector(".load-more-btn");let a=1,u="";b.addEventListener("submit",async function(o){o.preventDefault(),u=document.querySelector(".search-query").value,a=1,await f(u)});d.addEventListener("click",function(){a++,f(u,a)});async function f(o,s=1){p.style.display="flex";try{const n=(await y.get(L,{params:{key:g,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}})).data;if(a===1&&(i.innerHTML=""),o.trim()===""){l("Sorry, there are no images matching your search query. Please try again!");return}w(n.hits),s*15>=n.totalHits?(d.style.display="none",l("We're sorry, but you've reached the end of search results.")):d.style.display="block";const r=i.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy(0,r*2)}catch(t){l("An error occurred. Please try again."),console.error("Axios error:",t)}finally{p.style.display="none"}}function w(o){a===1&&(i.innerHTML=""),o.forEach(function(t){const n=document.createElement("div");n.classList.add("image-card"),n.innerHTML=`
            <a href="${t.largeImageURL}" data-lightbox="gallery">
                <img src="${t.webformatURL}" alt="${t.tags}">
            </a>
            <div class="image-info">
                <p>Likes: ${t.likes}</p>
                <p>Views: ${t.views}</p>
                <p>Comments: ${t.comments}</p>
                <p>Downloads: ${t.downloads}</p>
            </div>
        `,i.appendChild(n)}),new m(".image-card a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}function l(o){h.error({title:"Error",message:o||"An error occurred. Please try again."})}
//# sourceMappingURL=index.js.map
