import{a as f,S as m,i as h}from"./assets/vendor-DEenWwFD.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const c of t.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const g="47413838-05ed4088691502c79710d9d69",L="https://pixabay.com/api/",i=document.querySelector(".gallery"),b=document.querySelector(".search-form"),y=document.querySelector(".loader-container"),l=document.querySelector(".load-more-btn");let s=1,d="";b.addEventListener("submit",async function(o){o.preventDefault(),d=document.querySelector(".search-query").value,s=1,await p(d)});l.addEventListener("click",function(){s++,p(d,s)});async function p(o,a=1){y.style.display="flex";try{const n=(await f.get(L,{params:{key:g,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:a,per_page:15}})).data;s===1&&(i.innerHTML=""),v(n.hits),a*40>=n.totalHits?(l.style.display="none",u("We're sorry, but you've reached the end of search results.")):l.style.display="block";const e=i.querySelector(".image-card").getBoundingClientRect().height;window.scrollBy(0,e*2)}catch(r){u("An error occurred. Please try again."),console.error("Axios error:",r)}finally{y.style.display="none"}}function v(o){if(s===1&&(i.innerHTML=""),o.length===0||o.every(r=>r.toString().trim()==="")){u("Sorry, there are no images matching your search query. Please try again!");return}o.forEach(function(r){const n=document.createElement("div");n.classList.add("image-card"),n.innerHTML=`
            <a href="${r.largeImageURL}" data-lightbox="gallery">
                <img src="${r.webformatURL}" alt="${r.tags}">
            </a>
            <div class="image-info">
                <p>Likes: ${r.likes}</p>
                <p>Views: ${r.views}</p>
                <p>Comments: ${r.comments}</p>
                <p>Downloads: ${r.downloads}</p>
            </div>
        `,i.appendChild(n)}),new m(".image-card a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250}).refresh()}function u(o){h.error({title:"Error",message:o||"An error occurred. Please try again."})}
//# sourceMappingURL=index.js.map
